# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14uWNkRHOjvTgm8fPCTXdv0MFV1K23SH0
"""

import cv2
from matplotlib import pyplot as plt
import imutils
import easyocr
import numpy as np

path = '/Cars116.jpg'
image = cv2.imread(path)
gray = cv2.cvtColor(image,cv2.COLOR_BGR2GRAY)
plt.imshow(cv2.cvtColor(gray,cv2.COLOR_BGR2RGB))

bfilter = cv2.bilateralFilter(gray,11,17,17) ##noise reduction
edge = cv2.Canny(bfilter,30,200)             ##finding edges
plt.imshow(cv2.cvtColor(edge,cv2.COLOR_BGR2RGB))

points = cv2.findContours(edge.copy(),cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE) #finding coordinates 
con = imutils.grab_contours(points)
con = sorted(con,key=cv2.contourArea,reverse=True)[:10] #finding list of sorted area

location = None
for con in con:                     # iterating over each coordinate
  app = cv2.approxPolyDP(con,10,True)    # creating list of those coordinate whose area matchs rectangle
  if len(app) == 4:     # since rectangle will have 4 coordinate hence put this condition 
    location = app
    break

mask = np.zeros(gray.shape,np.uint8)      # creating a array equal to the orignal array of the image having only 0 pixel as value
new_image = cv2.drawContours(mask,[location],0,255,-1) # inserting the founded coordinate of the plate on the mask
new_image = cv2.bitwise_and(image, image, mask=mask)

plt.imshow(cv2.cvtColor(new_image,cv2.COLOR_BGR2RGB))

# finding x and y coordinate of the licence plate and cropping only that part of image and storing it in crop_img
(x,y) = np.where(mask==255)
(x1,y1) = (np.min(x),np.min(y))
(x2,y2) = (np.max(x),np.max(y))

crop_img = gray[x1:x2+1, y1:y2+1]

plt.imshow(cv2.cvtColor(crop_img,cv2.COLOR_BGR2RGB))

reader = easyocr.Reader(['en'])
result = reader.readtext(crop_img)
print(result)

text = result[0][-2]
print(text)
f = open('/sample.txt', 'w')
f.write('text')

sample = cv2.putText(img=image, text=text, org=(150, 250), fontFace=cv2.FONT_HERSHEY_TRIPLEX, fontScale=0.5, color=(0, 255, 0),thickness=1)
plt.imshow(cv2.cvtColor(sample,cv2.COLOR_BGR2RGB))